// <auto-generated />
using System;
using Foldrengesek2026.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Foldrengesek2026.Migrations
{
    [DbContext(typeof(FoldrengesContext))]
    partial class FoldrengesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Foldrengesek2026.Models.Naplo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("Ido")
                        .HasColumnType("time(6)");

                    b.Property<double>("Intenzitas")
                        .HasColumnType("double");

                    b.Property<double>("Magnitudo")
                        .HasColumnType("double");

                    b.Property<int>("TelepulesID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TelepulesID");

                    b.ToTable("Naplok");
                });

            modelBuilder.Entity("Foldrengesek2026.Models.Telepules", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Varmegye")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Telepulesek");
                });

            modelBuilder.Entity("Foldrengesek2026.Models.Naplo", b =>
                {
                    b.HasOne("Foldrengesek2026.Models.Telepules", "Telepules")
                        .WithMany("Naplok")
                        .HasForeignKey("TelepulesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Telepules");
                });

            modelBuilder.Entity("Foldrengesek2026.Models.Telepules", b =>
                {
                    b.Navigation("Naplok");
                });
#pragma warning restore 612, 618
        }
    }
}
